# set(CPACK_GENERATOR "DEB")

set(QGC_INSTALLER_SOURCE "${CMAKE_SOURCE_DIR}/deploy/linux")

# set(CPACK_DEB_COMPONENT_INSTALL 1)
# set(CPACK_DEBIAN_PACKAGE_NAME
# set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
# set(CPACK_DEBIAN_PACKAGE_EPOCH
# set(CPACK_DEBIAN_PACKAGE_VERSION
# set(CPACK_DEBIAN_PACKAGE_RELEASE
# set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
# set(CPACK_DEBIAN_PACKAGE_DEPENDS
# set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS
# set(CPACK_DEBIAN_PACKAGE_MAINTAINER
# set(CPACK_DEBIAN_PACKAGE_DESCRIPTION
# set(CPACK_DEBIAN_PACKAGE_SECTION
# set(CPACK_DEBIAN_ARCHIVE_TYPE "xz")
# set(CPACK_DEBIAN_COMPRESSION_TYPE
# set(CPACK_DEBIAN_PACKAGE_PRIORITY
# set(CPACK_DEBIAN_PACKAGE_HOMEPAGE
# set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS 1)
# set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS
# set(CPACK_DEBIAN_PACKAGE_DEBUG
# set(CPACK_DEBIAN_PACKAGE_PREDEPENDS
# set(CPACK_DEBIAN_PACKAGE_ENHANCES
# set(CPACK_DEBIAN_PACKAGE_BREAKS
# set(CPACK_DEBIAN_PACKAGE_CONFLICTS
# set(CPACK_DEBIAN_PACKAGE_PROVIDES
# set(CPACK_DEBIAN_PACKAGE_REPLACES
# set(CPACK_DEBIAN_PACKAGE_RECOMMENDS
# set(CPACK_DEBIAN_PACKAGE_SUGGESTS
# set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS
# set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY
# set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
# set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION
# set(CPACK_DEBIAN_PACKAGE_SOURCE

# set(CPACK_DEBIAN_DEBUGINFO_PACKAGE
